### PR TITLE
Add Plotly.NET.ImageExport project

### LINKED ISSUE #21: Add possibility to save charts as images programmatically
Creating images locally without having to open plots and click on the save as image button would be awesome. This however will take some work.

The only way i found to do this so far is using [Orca](https://github.com/plotly/orca), which is a command line utility that plotly itself uses to render images. Orca can be either installes as npm module, conda package, or deployed as a docker container. All of these add some overhead but i still think this is usefull. I will start to implement some functions to call orca functions and we will see how it goes.

### LINKED ISSUE #65: .Net Interactive using Svg (or other static) images?
### Description
I want to use pandoc to convert a f# .ipynb notebook containing Plotly.NET figures to pdf. However, the conversion does not show any figures in the pdf output. I think that the issue is that Plotly.NET.Interactive renders them using javascript that gets ignored by pandoc.

`pandoc notebook.ipynb -o notebook.html` works fine and includes figures. But `pandoc notebook.ipynb -o notebook.pdf` does not have any figures in it.

This resolved pandoc issue (https://github.com/jgm/pandoc/issues/6430) suggests that the conversion should be fine in python notebooks using  `plotly.io.renderers.default = "svg"`.

Can we allow a similar option in Plotly.NET.Interactive? Pandoc interop is useful because .net interactive does not have a way to save the file as a pdf or html file.

### Workarounds
A current workaround to get pdf output is to use pandoc to convert to html, then use the browser's save as pdf feature to product a pdf.

### LINKED ISSUE #90: Export Chart to SVG/PNG
Hi,
is there an easy way to export a plotted chart directly from code as PNG or SVG?
I tried it using the ".toChartImage" function from the api but didn't find a working solution yet.

### PR DESCRIPTION
**Pull request by kMutagene**
This PR adds the `Plotly.NET.ImageExport` project which is focused on providing extensions to save Plotly.NET's `GenericChart`s as static images. 

I designed the project with extensibility in mind. The needed steps to add a new renderer is:
1. Add a source file with a renderer implementing the `IGenericChartRenderer` interface
2. Add a DU representing your renderer to `ExportEngine` -> Done!

The currently provided Renderer uses `PuppeteerSharp` to use Chromium as headless browser and supports jpg, png, and svg export. It is heavily inspired by the work of @ilyalatt with https://github.com/ilyalatt/Plotly.NET.PuppeteerRenderer.

this PR eventually
closes #90 ,
closes #21 , 
and closes #65.

Addition of other engines will be tracked in a separate issue once this is merged.

ToDo:
- [x] add XML docs for API reference
- [x] add docs
- [x] investigate wether this library can be used for a static Image Kernel extension for dotnet interactive
- [x] Add nuget package metadata
- [x] Add fsdocs metadata

### CODE REVIEW

**Comment by kMutagene** [comment]
@ilyalatt please let me know if you want to be added as author to the nuget package that will be released from this eventually, as your work made this possible!

**Comment by ilyalatt** [comment]
> @ilyalatt please let me know if you want to be added as author to the nuget package that will be released from this eventually, as your work made this possible!

It is not important for me. I think current reference in the code is enough :)

**Comment by shuganth** [comment]
I am trying to save my plotly.Net chart to a jpg using Plotly.NET.ImageExport but when I try to do that there is no error but the code keeps running forever when it comes to the line maps.SaveJpg(path).
Can any please help ?Thanks
```
using Plotly.NET;
using Plotly.NET.ImageExport;

namespace Reports
{
    public class picture
    {

        public static void map()
        {
            string[] y = new string[] { "2.0", "1.5", "5.0", "1.5", "3.0", "5.0" };
            string[] x = new string[] { "Belarus", "Moldova", "Lithuania", "Russia", "Romania", "India" };
            
            var maps = ChartMap.Chart.ChoroplethMap<string, string>(locations: x, y, LocationMode: StyleParam.LocationFormat.CountryNames);
            maps.Show();
            string path = @"C:\Users\axx\Documents\Sucess";
            maps.SaveJPG(path); // It gets Stuck here :(
            Console.WriteLine("Done");
            
        }
    
        public static void Main(string[] args)
        {
            map();
        }
    }
}
```

**Comment by WhiteBlackGoose** [comment]
Hi, try using the async version please

**Comment by shuganth** [comment]
> Hi, try using the async version please

If I do that its moving to the next line but it's not saving the file.

**Comment by WhiteBlackGoose** [comment]
Did you use await?
```
await maps.SaveJpgAsync()
```

**Comment by shuganth** [comment]
> Did you use await?
> 
> ```
> await maps.SaveJpgAsync()
I'm a bit stuck here could you please help me out 

```       
            string[] y = new string[] { "2.0", "1.5", "5.0", "1.5", "3.0", "5.0" };
            string[] x = new string[] { "Belarus", "Moldova", "Lithuania", "Russia", "Romania", "India" };
            var maps = ChartMap.Chart.ChoroplethMap<string, string>(locations: x, y, LocationMode: StyleParam.LocationFormat.CountryNames);
            maps.Show();
            await maps.SaveJPGAsync("suvve");
```
Screenshot 2022-08-20 at 3 44 59 PM

**Comment by WhiteBlackGoose** [comment]
Uh, right. It's either that you're using an old version or we gracefully forgot to fix API for those methods. Could you try please try updating to the preview version. For it, open your cmd, cd to your project folder (e. g. `cd C:/users/you/project`) and there run
```
dotnet new nugetconfig
dotnet nuget add source https://www.myget.org/F/plotly-net-nightly/api/v3/index.json
dotnet add package Plotly.NET.ImageExport --prerelease
```

**Comment by shuganth** [comment]
> Uh, right. It's either that you're using an old version or we gracefully forgot to fix API for those methods. Could you try please try updating to the preview version. For it, open your cmd, cd to your project folder (e. g. `cd C:/users/you/project`) and there run
> 
> ```
> dotnet new nugetconfig
> dotnet nuget add source https://www.myget.org/F/plotly-net-nightly/api/v3/index.json
> dotnet add package Plotly.NET.ImageExport --prerelease
> ```

Its Worked thank you very much.

**Pull request merged**
